name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Apps/ACA/**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-311c0bdf-29cb-4351-9afc-3452a9e29801.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Apps/ACA 
          registryUrl: evolvable.azurecr.io
          registryUsername: ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: my-container-app
          resourceGroup: my-container-apps
          imageToBuild: evolvable.azurecr.io/my-container-app:${{ github.sha }}
          dockerfilePath: Dockerfile

     

